### PR TITLE
Use correct chunk comparison

### LINKED ISSUE #15: Version 2.0.0 is producing broken encoded polylines
I've just updated my site to use fast-polylines 2.0.0, and I'm seeing that it produces broken encoded polylines.

Here's what the map should look like:
correct

Here's what fast-polylines is producing:
incorrect

I've confirmed that the underlying GPS data is correct by running the coordinates through [polyline](https://github.com/mapbox/polyline) and displaying that resulting encoded polyline on the page & it matches the map from Strava.

The code that I use to generate the encoded polylines via fast-polylines is fairly simple:

```rb
points = coordinates.order("timestamp asc").map { |coordinate|
  [coordinate.latitude.to_f, coordinate.longitude.to_f]
}
encoded_polyline = FastPolylines.encode(points)
```

<details><summary>This activity's GPS coordinates</summary>

```
[[32.922315, -97.231877], [32.922315, -97.231877], [32.922315, -97.231877], [32.922315, -97.231877], [32.922315, -97.231877], [32.922315, -97.231877], [32.922315, -97.231877], [32.922315, -97.231877], [32.922249, -97.231943], [32.922218, -97.231945], [32.922207, -97.231943], [32.922183, -97.231941], [32.92217, -97.231938], [32.922158, -97.231935], [32.922145, -97.231932], [32.922132, -97.231928], [32.922119, -97.231922], [32.922042, -97.231889], [32.921922, -97.231862], [32.921895, -97.231862], [32.921835, -97.231873], [32.921713, -97.231894], [32.921613, -97.23189], [32.921551, -97.23187], [32.921514, -97.231871], [32.921495, -97.2319], [32.921486, -97.231914], [32.921479, -97.231923], [32.921437, -97.231941], [32.921261, -97.231958], [32.92113, -97.231876], [32.921123, -97.23165], [32.92107, -97.231489], [32.921068, -97.231471], [32.921051, -97.231442], [32.921037, -97.231416], [32.920977, -97.231213], [32.920964, -97.231113], [32.921043, -97.230958], [32.921224, -97.231022], [32.921414, -97.231039], [32.9216, -97.231051], [32.92177, -97.231117], [32.921874, -97.230923], [32.921877, -97.230703], [32.921879, -97.230484], [32.921875, -97.230327], [32.921876, -97.230113], [32.921873, -97.229973], [32.921882, -97.229757], [32.921871, -97.229529], [32.921904, -97.229315], [32.921841, -97.229228], [32.921651, -97.229282], [32.921626, -97.229285], [32.921617, -97.229287], [32.921435, -97.229307], [32.92133, -97.229304], [32.921148, -97.22931], [32.920962, -97.229292], [32.920809, -97.229315], [32.920699, -97.229299], [32.92051, -97.229267], [32.920459, -97.229375], [32.920616, -97.22948], [32.920789, -97.229514], [32.920793, -97.229527], [32.920785, -97.229575], [32.920763, -97.229797], [32.920754, -97.230013], [32.920753, -97.230207], [32.920751, -97.230255], [32.920754, -97.230336], [32.920736, -97.230546], [32.920743, -97.230764], [32.92076, -97.230988], [32.920769, -97.231199], [32.920768, -97.231273], [32.920814, -97.231481], [32.920867, -97.231692], [32.920882, -97.231908], [32.920876, -97.231943], [32.920892, -97.232002], [32.920897, -97.232178], [32.920934, -97.232389], [32.920939, -97.232401], [32.920952, -97.232433], [32.920952, -97.232457], [32.920956, -97.232467], [32.920963, -97.232469], [32.920968, -97.232492], [32.920969, -97.232503], [32.920969, -97.232516], [32.92097, -97.23253], [32.920951, -97.232748], [32.920951, -97.232829], [32.920977, -97.232988], [32.920972, -97.233083], [32.920994, -97.23322], [32.920997, -97.233256], [32.920989, -97.233338], [32.920972, -97.233553], [32.920982, -97.233776], [32.92096, -97.233997], [32.920956, -97.234211], [32.920945, -97.234441], [32.920954, -97.234663], [32.920951, -97.234883], [32.920938, -97.235002], [32.920923, -97.235221], [32.920857, -97.235421], [32.920824, -97.235637], [32.920823, -97.235647], [32.920863, -97.235659], [32.921055, -97.235678], [32.921239, -97.235696], [32.921423, -97.235709], [32.921608, -97.235684], [32.921796, -97.235672], [32.921977, -97.235673], [32.922169, -97.23567], [32.922353, -97.235657], [32.92247, -97.235667], [32.922493, -97.235873], [32.922463, -97.236093], [32.922475, -97.236312], [32.922461, -97.236532], [32.922467, -97.236749], [32.922468, -97.236752], [32.922482, -97.236817], [32.922486, -97.23704], [32.922469, -97.237265], [32.922481, -97.23748], [32.922364, -97.237596], [32.922332, -97.237602], [32.922227, -97.237603], [32.922047, -97.237594], [32.921867, -97.23759], [32.921742, -97.237587], [32.921561, -97.237607], [32.921425, -97.237609], [32.921401, -97.237608], [32.921379, -97.237611], [32.92124, -97.237617], [32.921208, -97.23761], [32.921023, -97.237588], [32.920912, -97.237611], [32.920772, -97.237478], [32.920808, -97.237258], [32.920822, -97.237044], [32.92081, -97.236837], [32.920806, -97.236612], [32.9208, -97.236393], [32.920804, -97.236177], [32.9208, -97.236047], [32.920812, -97.235889], [32.920792, -97.235779], [32.920684, -97.235772], [32.920642, -97.235773], [32.920462, -97.235799], [32.920286, -97.235845], [32.920108, -97.23591], [32.920064, -97.236108], [32.920068, -97.236243], [32.920057, -97.236464], [32.920077, -97.236687], [32.920075, -97.236913], [32.920065, -97.237127], [32.920061, -97.237351], [32.920069, -97.237456], [32.920002, -97.237642], [32.919954, -97.237655], [32.919898, -97.237652], [32.919709, -97.23763], [32.919523, -97.237615], [32.919338, -97.237634], [32.919221, -97.237502], [32.919217, -97.237283], [32.919218, -97.237063], [32.919215, -97.23687], [32.919215, -97.236648], [32.919177, -97.236432], [32.919126, -97.236215], [32.919106, -97.236], [32.919117, -97.23578], [32.919129, -97.235585], [32.91913, -97.235492], [32.919164, -97.235274], [32.919169, -97.235046], [32.919173, -97.234828], [32.919182, -97.234601], [32.919172, -97.234382], [32.919201, -97.234157], [32.919283, -97.233957], [32.919361, -97.233748], [32.919404, -97.233523], [32.919405, -97.233509], [32.919404, -97.233478], [32.919401, -97.23346], [32.919392, -97.233348], [32.919333, -97.233138], [32.919243, -97.232924], [32.919163, -97.232719], [32.919142, -97.232645], [32.919139, -97.232595], [32.919141, -97.232544], [32.919151, -97.232467], [32.919154, -97.232444], [32.919158, -97.232422], [32.919151, -97.232318], [32.91916, -97.232309], [32.919233, -97.232314], [32.919254, -97.232317], [32.91927, -97.23232], [32.919284, -97.23233], [32.919295, -97.232391], [32.919294, -97.232518], [32.919286, -97.232734], [32.919435, -97.232847], [32.919621, -97.232863], [32.91981, -97.232855], [32.91998, -97.232855], [32.920002, -97.232857], [32.920182, -97.232879], [32.920314, -97.232889], [32.920392, -97.232887], [32.920564, -97.232872], [32.920629, -97.232881], [32.920639, -97.232883], [32.920659, -97.232883], [32.920754, -97.232899], [32.920934, -97.232868], [32.921105, -97.232785], [32.921111, -97.232766], [32.921115, -97.232744], [32.921117, -97.232719], [32.921128, -97.232506], [32.921122, -97.232452], [32.921127, -97.23241], [32.921159, -97.232298], [32.921156, -97.23226], [32.921135, -97.232095], [32.921134, -97.23205], [32.921133, -97.231975], [32.921138, -97.231978], [32.921183, -97.231981], [32.921196, -97.231977], [32.921375, -97.231979], [32.92156, -97.232001], [32.921674, -97.232028], [32.921764, -97.232036], [32.92181, -97.232031], [32.921979, -97.232011], [32.922129, -97.23202], [32.922278, -97.232018], [32.922274, -97.232107], [32.922264, -97.232331], [32.922264, -97.232548], [32.922216, -97.23275], [32.922041, -97.232777], [32.92185, -97.232753], [32.921707, -97.232744], [32.921643, -97.232798], [32.921819, -97.232865], [32.922005, -97.232901], [32.9222, -97.232909], [32.922343, -97.232971], [32.92234, -97.233043], [32.922286, -97.23325], [32.922288, -97.233465], [32.922285, -97.233692], [32.92227, -97.233729], [32.922096, -97.233748], [32.921915, -97.233736], [32.92176, -97.233725], [32.921649, -97.233747], [32.921645, -97.233776], [32.921645, -97.233786], [32.921665, -97.233811], [32.921847, -97.23387], [32.922039, -97.233864], [32.922223, -97.233872], [32.922297, -97.234016], [32.922277, -97.234238], [32.922133, -97.234322], [32.922, -97.234299], [32.921821, -97.234298], [32.921761, -97.234418], [32.921908, -97.234516], [32.922074, -97.234423], [32.922244, -97.234479], [32.922412, -97.234461], [32.922422, -97.234247], [32.922396, -97.234025], [32.922397, -97.233807], [32.922408, -97.23359], [32.922441, -97.233373], [32.922456, -97.233147], [32.922462, -97.232929], [32.922458, -97.232714], [32.922464, -97.232514], [32.922505, -97.23232], [32.922602, -97.232301], [32.922611, -97.232299], [32.9228, -97.232283], [32.922891, -97.23213], [32.922905, -97.23191], [32.922902, -97.231832]]
```

</details>

<details><summary>The encoded polyline from fast-polylines</summary>

```
mc}gEfrmpQ??????????????JJD@@AD?@?@?@AB?@ANEVEB?J@XBR?JCF?@D@@@@FBb@BXO@m@H_?CBE@CJi@BSO]c@Je@Be@@a@LSg@Ak@?k@?]?k@@[Ai@@m@Ei@JQd@HB@@?b@BTAb@@d@C\\DTCd@EHT_Ra@D?B?HDj@@h@?f@?H?N@h@?h@Cl@Ah@?LGh@Kh@Aj@?DAJAb@Eh@A@AD?DA@??AB?@?B?@Bj@?NE^@PCZAF@NBh@Al@Bj@?h@@l@?j@?j@@VBj@Jf@Fj@?@G@g@Bc@Bc@@e@Ee@Ac@?e@?c@AW@Cf@Dj@Cj@Bj@Aj@??ALAj@Bl@Ah@VVD?R?b@Ab@?X?b@BX?D?B?Z@DAd@CTBZYGk@Ak@@g@?m@@k@?i@?YA_BUTAF?b@D`@Hb@JHf@AX@j@Cl@@j@?j@@j@ATLb@HBHAd@Cd@Ab@@VY?k@?k@?e@?k@Fk@Hi@Bk@Ak@Ae@?SEk@Ak@?k@Am@@k@Ek@Og@Oi@Gm@?A?E?C@UJi@Pk@Ng@BM?I?KAM?EAC@SAAM?C@C?A@CJ@X?h@]Vc@@e@?a@?C?c@BY@O?a@CM@A?C?QBc@Ea@OACAE?CAi@@KAGEU?GB_@I?MA?G?C?a@?e@BUDQ@IAa@C]@]?@P@j@?j@Ff@b@Dd@EZALJc@Le@De@@[J?LHh@?j@?j@BF`@Bb@A^ATB?D?@ABe@Je@Ac@@O\\Bj@\\NXCb@?JV]R_Sa@Ja@CAi@Bk@?k@Ak@Ek@Ck@?k@?k@?g@Ie@QCA?e@CQ]Ck@@O
```

</details>

<details><summary>The encoded polyline from polyline</summary>

```
mc}gEfrmpQ??????????????JJD@@AD?@?@?@AB?@ANEVEB?J@XBR?JCF?@D@@@@FBb@BXO@m@H_?CBE@CJi@BSO]c@Je@Be@@a@LSg@Ak@?k@?]?k@@[Ai@@m@Ei@JQd@HB@@?b@BTAb@@d@C\\DTCd@EHT_Ra@D?B?HDj@@h@?f@?H?N@h@?h@Cl@Ah@?LGh@Kh@Aj@?DAJAb@Eh@A@AD?DA@??AB?@?B?@Bj@?NE^@PCZAF@NBh@Al@Bj@?h@@l@?j@?j@@VBj@Jf@Fj@?@G@g@Bc@Bc@@e@Ee@Ac@?e@?c@AW@Cf@Dj@Cj@Bj@Aj@??ALAj@Bl@Ah@VVD?R?b@Ab@?X?b@BX?D?B?Z@DAd@CTBZYGk@Ak@@g@?m@@k@?i@?YA_BUTAF?b@D`@Hb@JHf@AX@j@Cl@@j@?j@@j@ATLb@HBHAd@Cd@Ab@@VY?k@?k@?e@?k@Fk@Hi@Bk@Ak@Ae@?SEk@Ak@?k@Am@@k@Ek@Og@Oi@Gm@?A?E?C@UJi@Pk@Ng@BM?I?KAM?EAC@SAAM?C@C?A@CJ@X?h@]Vc@@e@?a@?C?c@BY@O?a@CM@A?C?QBc@Ea@OACAE?CAi@@KAGEU?GB_@I?MA?G?C?a@?e@BUDQ@IAa@C]@]?@P@j@?j@Ff@b@Dd@EZALJc@Le@De@@[J?LHh@?j@?j@BF`@Bb@A^ATB?D?@ABe@Je@Ac@@O\\Bj@\\NXCb@?JV]R_Sa@Ja@CAi@Bk@?k@Ak@Ek@Ck@?k@?k@?g@Ie@QCA?e@CQ]Ck@@O
```

</details>

### PR DESCRIPTION
**Pull request by BuonOmo**
Fixes #15

Also in this pull request:
- Add more debugging information in C
- Add security for bad inputs such as
  ```ruby
  FastPolylines.encode([1.2, 1.2])
  ```

The security part slows down a tiny bit the `FastPolylines.encode`
method. However it avoids a core dump.

### CODE REVIEW

File: ext/fast_polylines/fast_polylines.c [hunk 1]
```diff
@@ -72,15 +72,18 @@ rb_FastPolylines__decode(int argc, VALUE *argv, VALUE self) {
 
 static inline uint8_t
 _polyline_encode_number(char *chunks, int64_t number) {
+	dbg("_polyline_encode_number(\"%s\", %lli)\n", chunks, number);
 	number = number < 0 ? ~(number << 1) : (number << 1);
 	uint8_t i = 0;
-	while (number > 0x20) {
+	while (number >= 0x20) {
```
Comment (BuonOmo) [inline ext/fast_polylines/fast_polylines.c:78]: Here is the fix.

File: ext/fast_polylines/fast_polylines.c [hunk 2]
```diff
@@ -108,6 +111,7 @@ rb_FastPolylines__encode(int argc, VALUE *argv, VALUE self) {
 	for (i = 0; i < len; i++) {
 			current_pair = RARRAY_AREF(argv[0], i);
 			uint8_t j;
+			Check_Type(current_pair, T_ARRAY);
```
Comment (BuonOmo) [inline ext/fast_polylines/fast_polylines.c:114]: And here is the security check.

**Review by pyrsmk — APPROVED** [review]

**Review by Quiwin — APPROVED** [review]
LGTM

**Comment by BuonOmo** [comment]
[(5) [OS] Fix fast-polylines](https://trello.com/c/y33xuXrb/848-5-os-fix-fast-polylines)
